
### yml
### str
GET http://{{host}}:{{port}}/demo/init/yml/str
Accept: application/json
token: {{token}}

### list
GET http://{{host}}:{{port}}/demo/init/yml/strList
Accept: application/json
token: {{token}}

###
GET http://{{host}}:{{port}}/demo/init/yml/filePath
Accept: application/json
token: {{token}}

