# mkdir -p ./docker/logs && mkdir -p ./docker/logs && mvn clean package -Dmaven.test.skip=true && docker-compose up --build
# version 参考：https://docs.docker.com/compose/compose-file/#reference-and-guidelines
# compose https://docs.docker.com/compose/
version: '3.7'
# 可以指定多个服务
services:
  oneforall:
    build: .
    container_name: oneforall-bdy
    image: oneforall-bdy:latest # Error response from daemon: no such image: OneForAll:latest: invalid reference format: repository name must be lowercase
    restart: 'no'
    ports:
      - 8080:8080 # 前linux端口，后docke启动镜像的端口
    environment:
      LOG_HOME: byd_log_home
      JAVA_OPTS: # 配置 jvm 参数 -Ddruid.mysql.usePingMethod=false
        -Dlog.home=/app
    volumes:
      - './docker/logs:/app/logs'
      - './docker/files:/app/files'
    network_mode: bridge
  # 同一级别的可以配置多个
