

### 1. queryString
GET http://{{host}}:{{port}}/demo/param/reqParam?param=abc
Accept: application/json
token: {{token}}

### 2. queryString
GET http://{{host}}:{{port}}/demo/param/reqEnumParam?param=1
Accept: application/json
token: {{token}}


### 2. dto
GET http://{{host}}:{{port}}/demo/param/reqDto?name=abc&description=description
Accept: application/json
token: {{token}}

### 3. rest
GET http://{{host}}:{{port}}/demo/param/rest/abcd
Accept: application/json
token: {{token}}

### 4. restWith
GET http://{{host}}:{{port}}/demo/param/restWith/abcd?param=param
Accept: application/json
token: {{token}}

### 5. post-string
POST http://{{host}}:{{port}}/demo/param/postJson
Accept: application/json
token: {{token}}

ABC

### 6. post-dto paramDto.toString()
PUT http://{{host}}:{{port}}/demo/param/postObj
Accept: application/json
Content-Type: application/json
username: true
token: {{token}}

{
"name": "name",
 "statusEnum": "3",
"description": "description"
}

### 7. post file
POST http://{{host}}:{{port}}/demo/param/postFile
Content-Type: multipart/form-data; boundary=WebAppBoundary
token: {{token}}

--WebAppBoundary
Content-Disposition: form-data; name="field-name"; filename="1.png"

< E:\filesystem\upload\001.png
--WebAppBoundary--

###