GET http://{{host}}:{{port}}/common/menu/test
Accept: application/json
token: {{token}}
### topMenu
GET http://{{host}}:{{port}}/common/menu/menu
Accept: application/json
token: {{token}}

###拿到 某个业务分类
GET http://{{host}}:{{port}}/common/menu/menu/TYPE/8c832f78212748c0b4be46e36c36ffaa
Accept: application/json
token: {{token}}

### 业务分类的目录
### f4f88902da37406caf000c899f8b522f 786f7877a3154383b93453c997d7ed7b
GET http://{{host}}:{{port}}/common/menu/picmenu/BUSI/786f7877a3154383b93453c997d7ed7b
Accept: application/json
token: {{token}}

### 目录中的数据 25d3918aa1fc4f6e84f2c06b9f9313de yane羽毛
GET http://{{host}}:{{port}}/common/menu/picdata/BUSI/25d3918aa1fc4f6e84f2c06b9f9313de
Accept: application/json
token: {{token}}

### 取数据库查询具体的 媒体数据
