spring:
  mvc:
    view:
      prefix: /
      suffix: .html
  servlet:
    multipart:
      max-file-size: 10240000000
      max-request-size: 10240000000
server:
  port: 8081
  tomcat:
    connection-timeout: 1s