

###
GET http://localhost:8080/config/str
Accept: application/json

###
GET http://localhost:8081/demo/yml/strList
Accept: application/json

###
GET http://localhost:8081/init/getfun
Accept: application/json

### /demo/properties
GET http://localhost:8081/demo/properties/map
Accept: application/json
