GET http://localhost:80/common/accounts/findAll
Accept: application/json

### insert main
GET http://localhost:80/common/accounts/addmain
Accept: application/json

{
"webroot": "https://www.jokerlu6.pw/",
"webname": "jokerlu",
"softtype": "web",
"webtype": "AV",
"vip": "0"
}

### insert sub
GET http://localhost:80/common/accounts/addtag
Accept: application/json

{
"weburl": "https://www.xuefeiw.com/html/10182.html",
"webrootname": "飞雪娱乐网",
"webname": "【ADV】 我的女友是工薪 民工女友 汉化版 归档 【1.8G】【百度云下载】",
"softtype": "web",
"webtype": "软件"
}

### data
GET http://localhost:80/common/accounts/addtag
Accept: application/json

{
"weburl": "https://www.xuefeiw.com/html/10182.html",
"webrootname": "飞雪娱乐网",
"webname": "【ADV】 我的女友是工薪 民工女友 汉化版 归档 【1.8G】【百度云下载】",
"softtype": "web",
"webtype": "软件"
}