
### 所有相册
GET http://{{host}}:{{port}}/local/craw/bilalbum/allalbum/252341715
Accept: application/json

### 查看是否完成
GET http://{{host}}:{{port}}/local/craw/bilalbum/existsTask
Accept: application/json

### 测试文件
GET http://{{host}}:{{port}}/local/craw/bilalbum/tsave/123
Accept: application/json
