### thymeleaf
POST http://{{host}}:{{port}}/demo/mail/testMailThymeleaf
Content-Type: application/json
token: {{token}}

{
  "subject": "主题-thymeleaf",
  "from": "718497737@qq.com",
  "toMail": "wang18839118972@126.com",
  "context": {
    "username": "username",
    "num": "num",
    "salary": "99999"
  }
}

### freemarker
POST http://{{host}}:{{port}}/demo/mail/testMailFreemarker
Content-Type: application/json
token: {{token}}

{
  "subject": "主题-freemarker",
  "from": "718497737@qq.com",
  "toMail": "wang18839118972@126.com",
  "context": {
    "username": "username",
    "num": "num",
    "salary": "99999"
  }
}