### webapi 获取用户信息
### method 固定 uinfo
### access_token 用户token
GET https://pan.baidu.com/rest/2.0/xpan/nas?method=uinfo&access_token=121.85a568e448d5ad462d6cb7767213f4f1.Y3h2wbrPks0TNvY9c31pP5Ow1N-VffmzkfkXHrO.uwt9TA

### 1. 获取用户信息
GET http://{{host}}:{{port}}/common/bddisk/uinfo/info/false
Accept: application/json
token: {{token}}

### webapi 获取网盘容量信息
### checkfree int 1 是否检查免费信息，0为不查，1为查，默认为0
### checkexpire int 1 是否检查过期信息，0为不查，1为查，默认为0
GET https://pan.baidu.com/api/quota?checkfree=1&checkexpire=1&access_token=121.85a568e448d5ad462d6cb7767213f4f1.Y3h2wbrPks0TNvY9c31pP5Ow1N-VffmzkfkXHrO.uwt9TA

### 2. 获取网盘容量信息

