### 1. 引导用户认证地址
GET http://{{host}}:{{port}}/common/bddisk/auth/getUserAuthUrl
token: {{token}}
Accept: application/json

### code 181b9e4c6f563c9c2240e1edc7511889
### 3. 用code换access_token
GET http://{{host}}:{{port}}/common/bddisk/auth/getUserAuthUrl/false/181b9e4c6f563c9c2240e1edc7511889
Accept: application/json
### lc
token: {{token}}
### gkl
### token: {{token}}

### 4. 测试/刷新access_token
#GET http://{{ip}}:{{port}}/common/bddisk/auth/refreshAccessToken/122.0df751fad3853c9c6c6ad58934620dad.YQ1phERmOH-75S-CO1-edFtPGu3D0XJc8TsLFQ-.u5-1GQ
#Accept: application/json
#token: {{token}}

### 5. 正式给其他接口token刷新的接口
GET http://{{host}}:{{port}}/common/bddisk/auth/getBDDiskToken
Accept: application/json
token: {{token}}
