POST http://{{host}}:{{port}}/open/validated/validate
Accept: application/json
token: {{token}}

{
    "name": "文件名名名1",
    "strLength": "文件名名名文件名名名",
    "withOutGroup": "文件名名名文件名名名名111111",
    "innerObj": {
        "strLength": "inner-strL",
        "strRegex": "aa#"
    }
}

### 测试数据
{
    "name": "文件名名名1",
    "strLength": "文件名名名文件名名名",
    "withOutGroup": "文件名名名文件名名名名111111",
    "innerObj": {
        "strLength": "inner-strL"
    }
}

###
POST http://{{host}}:{{port}}/open/validated/validateWithOut
Accept: application/json
token: {{token}}

{
"name": "文件名名名1",
"strLength": "文件名名名文件名名名",
"withOutGroup": "文件名名名文件名名名名111111"
}

###
GET http://{{host}}:{{port}}/demo/validated/ps/4
Accept: application/json
token: {{token}}

###
