### 1. 查看已有的卡池
GET http://{{host}}:{{port}}/b/game/drawcard/findGame
Accept: application/json
token: {{token}}

### 2. 抽卡
GET http://{{host}}:{{port}}/b/game/drawcard/play/bb018eb4fdb342d589590d460638115d
Accept: application/json
token: {{token}}

### 3. 抽卡记录
GET http://{{host}}:{{port}}/b/game/drawcard/playrecoder/bb018eb4fdb342d589590d460638115d
Accept: application/json
token: {{token}}
