POST http://{{host}}:{{port}}/common/upload/write
Content-Type: multipart/form-data; boundary=WebAppBoundary; charset=utf-8
User-Agent: PostmanRuntime/7.29.0
Accept-Encoding: gzip, deflate, br
token: {{token}}

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="002.png"
Content-Type: audio/mpeg


< E:\filesystem\upload\002.png
--WebAppBoundary--


###
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="水晶蝶 - 情动 - 副本.mp3"
Content-Type: audio/mpeg


< E:\test\水晶蝶 - 情动 - 副本.mp3
--WebAppBoundary--
token: {{token}}

