###
### http://{{ip}}:{{port}}/open/file/read/down/test.mp3
GET http://{{host}}:{{port}}/open/file/read/down/uname
Accept: application/json
token: {{token}}
###
GET http://{{host}}:{{port}}/common/file/read/returnTXT
Accept: application/json
token: {{token}}
###