POST http://{{host}}:{{port}}/open/file/upload/write
Content-Type: multipart/form-data; boundary=WebAppBoundary; charset=utf-8
Accept-Encoding: gzip, deflate, br

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="1652338908954.png"
Content-Type: audio/mpeg


< E:\filesystem\test\1652338908954.png
--WebAppBoundary--


###
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="水晶蝶 - 情动 - 副本.mp3"
Content-Type: audio/mpeg


< E:\test\水晶蝶 - 情动 - 副本.mp3
--WebAppBoundary--
token: {{token}}

